from django.urls import path
from .views import (
    HealthView, PlayView, StartGameView, 
    DebugPageView, StepGameView, StartCombatView, 
    CombatActionView, AdventureListView, LandingPageView,
    PlayPageView, CharacterCreatePageView, CurrentGameStateView, CombatPageView,
    CombatStateView, GameOverPageView, SignupView,
    SaveGameListView, LoadSaveGameView, DeleteSaveGameView,
    VictoryPageView, CharacterCreationOptionsView, DevAccountDashboardView,
    CharacterTemplateListView, CharacterTemplateSaveView,
    CharacterTemplateDeleteView, CurrentRoomView, StoryTurnMetricView)
from .dataset_api import (
    DatasetApiDocsView,
    DatasetOpenApiView,
    IngestionRunSummaryView,
    MonsterCollectionView,
    MonsterDetailView,
)

urlpatterns = [
    path("", LandingPageView.as_view(), name="landing"),
    path("accounts/signup/", SignupView.as_view(), name="signup"),
    path("character/create/", CharacterCreatePageView.as_view(), name="character_create"),
    path("play/", PlayPageView.as_view(), name="play"),
    path("health", HealthView.as_view(), name="health"),
    path("debug", DebugPageView.as_view(), name="debug"),
    path("_dev/accounts/", DevAccountDashboardView.as_view(), name="dev_accounts"),
    path("api/adventures/", AdventureListView.as_view(), name="api_adventures"),
    path("api/v1/monsters/", MonsterCollectionView.as_view(), name="api_v1_monsters"),
    path("api/v1/openapi.yaml", DatasetOpenApiView.as_view(), name="api_v1_openapi"),
    path("api/v1/docs/", DatasetApiDocsView.as_view(), name="api_v1_docs"),
    path(
        "api/v1/monsters/<int:monster_id>/",
        MonsterDetailView.as_view(),
        name="api_v1_monster_detail",
    ),
    path(
        "api/v1/ingestion-runs/<str:run_id>/summary/",
        IngestionRunSummaryView.as_view(),
        name="api_v1_ingestion_run_summary",
    ),
    path("api/character-options/", CharacterCreationOptionsView.as_view(), name="api_character_options"),
    path("api/character-templates/", CharacterTemplateListView.as_view(), name="api_character_templates"),
    path("api/character-templates/save", CharacterTemplateSaveView.as_view(), name="api_character_template_save"),
    path("api/character-templates/<int:template_id>/delete", CharacterTemplateDeleteView.as_view(), name="api_character_template_delete"),
    path("api/saves/", SaveGameListView.as_view(), name="api_saves"),
    path("api/saves/<int:save_game_id>/load", LoadSaveGameView.as_view(), name="api_save_load"),
    path("api/saves/<int:save_game_id>/delete", DeleteSaveGameView.as_view(), name="api_save_delete"),
    path("api/play", PlayView.as_view(), name="api_play"),
    path("api/start", StartGameView.as_view(), name="api_start"),
    path("api/step", StepGameView.as_view(), name="api_step"),
    path("api/metrics/story-turn", StoryTurnMetricView.as_view(), name="api_story_turn_metric"),
    path("api/current-room", CurrentRoomView.as_view(), name="api_current_room"),
    path("api/combat/start", StartCombatView.as_view(), name="api_combat_start"),
    path("api/combat/action", CombatActionView.as_view(), name="api_combat_action"),
    path("combat/", CombatPageView.as_view(), name="combat"),
    path("gameover/", GameOverPageView.as_view(), name="gameover"),
    path("victory/", VictoryPageView.as_view(), name="victory"),
    path("api/combat/state/", CombatStateView.as_view(), name="api_combat_state"),
    path("api/state/", CurrentGameStateView.as_view(), name="api_state"),
]
