"""
Django settings for call_to_aidventure project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes", "on"}
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError("DJANGO_SECRET_KEY is required when DJANGO_DEBUG is false")
    SECRET_KEY = "django-insecure-development-only-change-me"

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,0.0.0.0,host.docker.internal",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django_prometheus",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "game"
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = 'call_to_aidventure.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'call_to_aidventure.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_prometheus.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Read-only certification dataset built by ``python -m data_pipeline``.
DATASET_DB_PATH = os.getenv(
    "DB_PATH", str(PROJECT_ROOT.parent / "db" / "sqlite" / "data.db")
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ("en", "English"),
    ("fr", "Français"),
]

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


def env_bool(name, default):
    value = os.getenv(name, default)
    return str(value).lower() in {"1", "true", "yes", "on"}


def env_int(name, default):
    return int(os.getenv(name, default))


def env_float(name, default):
    return float(os.getenv(name, default))


def env_csv(name, default):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


LLM_REQUEST_TIMEOUT_SECONDS = env_float("LLM_REQUEST_TIMEOUT_SECONDS", "30")
LLM_PROVIDER_MAX_RETRIES = env_int("LLM_PROVIDER_MAX_RETRIES", "0")
LLM_RETRY_MAX_ATTEMPTS = env_int("LLM_RETRY_MAX_ATTEMPTS", "3")
LLM_RETRY_INITIAL_DELAY_SECONDS = env_float("LLM_RETRY_INITIAL_DELAY_SECONDS", "0.5")
LLM_RETRY_BACKOFF_MULTIPLIER = env_float("LLM_RETRY_BACKOFF_MULTIPLIER", "2")
LLM_RETRY_MAX_DELAY_SECONDS = env_float("LLM_RETRY_MAX_DELAY_SECONDS", "4")
LLM_RETRY_JITTER_SECONDS = env_float("LLM_RETRY_JITTER_SECONDS", "0.25")
LLM_TRANSIENT_ERROR_KEYWORDS = env_csv(
    "LLM_TRANSIENT_ERROR_KEYWORDS",
    "timeout,timed out,rate limit,too many requests,temporarily unavailable,service unavailable,"
    "connection error,connection reset,connection aborted,server error,internal server error,"
    "bad gateway,gateway timeout,try again",
)
LLM_TRANSIENT_STATUS_CODES = [
    int(status_code)
    for status_code in env_csv("LLM_TRANSIENT_STATUS_CODES", "408,409,425,429,500,502,503,504")
]
LLM_SERVICE_UNAVAILABLE_STATUS_CODE = env_int("LLM_SERVICE_UNAVAILABLE_STATUS_CODE", "503")
LLM_SERVICE_UNAVAILABLE_MESSAGE = os.getenv(
    "LLM_SERVICE_UNAVAILABLE_MESSAGE",
    "The storyteller is temporarily unavailable. Your adventure is safe; please try again in a moment.",
)
MAX_JSON_BODY_BYTES = env_int("MAX_JSON_BODY_BYTES", "8192")
AI_RATE_LIMIT_REQUESTS = env_int("AI_RATE_LIMIT_REQUESTS", "12")
AI_RATE_LIMIT_WINDOW_SECONDS = env_int("AI_RATE_LIMIT_WINDOW_SECONDS", "300")

if not DEBUG and not os.getenv("DJANGO_ALLOWED_HOSTS"):
    raise RuntimeError("DJANGO_ALLOWED_HOSTS is required when DJANGO_DEBUG is false")

SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", "false" if DEBUG else "true")
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", "false" if DEBUG else "true")
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", "false" if DEBUG else "true")
SECURE_HSTS_SECONDS = env_int("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "31536000")
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    "false" if DEBUG else "true",
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", "false" if DEBUG else "true")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = env_csv("DJANGO_CSRF_TRUSTED_ORIGINS", "")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "structured": {
            "format": "time={asctime} level={levelname} logger={name} message={message}",
            "style": "{",
        },
    },
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "structured"}},
    "loggers": {
        "agents": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "retrieval": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
