"""
Django settings for call_to_aidventure project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e1+@%(y$z**z*k0qe0(8-gw2s$5e^3j)^^b1tff5i$c=mr=-a7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "game"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'call_to_aidventure.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'call_to_aidventure.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


def env_int(name, default):
    return int(os.getenv(name, default))


def env_float(name, default):
    return float(os.getenv(name, default))


def env_csv(name, default):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


LLM_REQUEST_TIMEOUT_SECONDS = env_float("LLM_REQUEST_TIMEOUT_SECONDS", "30")
LLM_PROVIDER_MAX_RETRIES = env_int("LLM_PROVIDER_MAX_RETRIES", "0")
LLM_RETRY_MAX_ATTEMPTS = env_int("LLM_RETRY_MAX_ATTEMPTS", "3")
LLM_RETRY_INITIAL_DELAY_SECONDS = env_float("LLM_RETRY_INITIAL_DELAY_SECONDS", "0.5")
LLM_RETRY_BACKOFF_MULTIPLIER = env_float("LLM_RETRY_BACKOFF_MULTIPLIER", "2")
LLM_RETRY_MAX_DELAY_SECONDS = env_float("LLM_RETRY_MAX_DELAY_SECONDS", "4")
LLM_RETRY_JITTER_SECONDS = env_float("LLM_RETRY_JITTER_SECONDS", "0.25")
LLM_TRANSIENT_ERROR_KEYWORDS = env_csv(
    "LLM_TRANSIENT_ERROR_KEYWORDS",
    "timeout,timed out,rate limit,too many requests,temporarily unavailable,service unavailable,"
    "connection error,connection reset,connection aborted,server error,internal server error,"
    "bad gateway,gateway timeout,try again",
)
LLM_TRANSIENT_STATUS_CODES = [
    int(status_code)
    for status_code in env_csv("LLM_TRANSIENT_STATUS_CODES", "408,409,425,429,500,502,503,504")
]
LLM_SERVICE_UNAVAILABLE_STATUS_CODE = env_int("LLM_SERVICE_UNAVAILABLE_STATUS_CODE", "503")
LLM_SERVICE_UNAVAILABLE_MESSAGE = os.getenv(
    "LLM_SERVICE_UNAVAILABLE_MESSAGE",
    "The storyteller is temporarily unavailable. Your adventure is safe; please try again in a moment.",
)
