# Generated by Codex on 2026-05-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savegame",
            unique_together=set(),
        ),
    ]
