# Generated by Codex on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_savegame_unique_adventure"),
    ]

    operations = [
        migrations.AddField(
            model_name="savegame",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savegame",
            name="is_finished",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
