"""Generate E4/E5 editable presentations and PDFs using the established visual style."""
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

OUT=Path(__file__).resolve().parent
BG,PANEL,WHITE,MUTED,ACCENT,GOLD='101C2B','1C2C40','F4F6FA','B5C2D3','60DFBD','F2C879'
e1=(OUT.parent/'presentation-e1/generate_slides.py').read_text(encoding='utf-8-sig')
exec(e1[e1.index('def rect('):e1.index("notes=['# Notes orales")])
e2=(OUT.parent/'presentation-bloc2/generate_slides.py').read_text(encoding='utf-8-sig')
exec(e2[e2.index('def render('):e2.index("assert sum(s['seconds']")])
pdfmetrics.registerFont(TTFont('Deck','C:/Windows/Fonts/arial.ttf'))
pdfmetrics.registerFont(TTFont('DeckBold','C:/Windows/Fonts/arialbd.ttf'))
slides=[]
def add(part,tag,title,subtitle,cards,takeaway,source,notes):
    slides.append(dict(part=part,tag=tag,title=title,subtitle=subtitle,cards=cards,takeaway=takeaway,source=source,notes=notes,seconds=100 if part=='E4' else 75 if part=='E5' else 0))

add('E4','E4 · C14 À C19','Construire une application intégrant l’IA','Call To AIdventure · Bloc 3 · E4 : 20 minutes',
 [('PRODUIT','Une aventure interactive dans le navigateur, avec narration IA et règles de jeu côté serveur.'),('RÉALISATION','Cadrer, concevoir, organiser et développer les parcours du joueur.'),('QUALITÉ / LIVRAISON','Tester le métier et les accès.\nAutomatiser les contrôles.\nPréparer un artefact déployable.')],
 'Le bloc 3 relie les besoins du joueur aux preuves de fonctionnement.', 'Référentiel 2023, p. 16–21 ; règlement, p. 12',
 'Présenter identité, rôle, commanditaire et contexte scolaire. Le passage isolé du bloc prévoit E4 20 minutes, E5 10 minutes, puis 10 minutes de questions. Personnaliser les contributions réelles et les éventuelles aides reçues. Les slides ne remplacent pas le rapport E4 ni les documentations E5.')
add('E4','C14 · BESOIN ET UTILISATEURS','Permettre de jouer et de retrouver sa progression','Les parcours distinguent le visiteur et le joueur connecté.',
 [('VISITEUR','Choisir une aventure.\nCréer un personnage valide.\nJouer sans créer de compte.\nProgression liée à la session.'),('JOUEUR CONNECTÉ','Retrouver ses sauvegardes.\nReprendre une partie active.\nRéutiliser ses personnages.\nGérer ses propres données.'),('EXPLOITANT / JURY','Installer et vérifier le service.\nComprendre les choix techniques.\nRelier exigences, code, tests et démonstration.')],
 'La continuité de la partie et la propriété des données orientent la conception.', 'docs/block3/project-brief-requirements.md',
 'Expliquer les acteurs et la valeur du service avant la technologie. La session anonyme n’offre pas la même reprise durable qu’une sauvegarde authentifiée. Le commanditaire et les contraintes de volume/budget restent à confirmer dans le document de cadrage ; ne pas les inventer.')
add('E4','C14 · SPÉCIFICATIONS','Transformer le besoin en critères vérifiables','Exemples issus des exigences et des tests du projet.',
 [('REPRENDRE SA PARTIE','Un joueur peut charger sa sauvegarde active.\nUn autre utilisateur ne peut ni la charger ni la supprimer.'),('SURVIVRE À UNE PANNE','Un tour IA en échec retourne une erreur contrôlée.\nLa progression sauvegardée ne doit pas avancer.'),('UTILISER L’INTERFACE','Navigation et états compréhensibles.\nCritères clavier, focus et annonces.\nCible d’accessibilité à valider.')],
 'Chaque exigence doit avoir un composant, un test et une preuve de démonstration.', 'docs/block3/traceability.md ; project-brief-requirements.md',
 'Relier FR-10 à SaveGame, NFR-06 aux filtres de propriétaire et NFR-07 à la frontière de persistance. Les critères d’accessibilité doivent être intégrés aux user stories et associés à un standard choisi. Une cible WCAG/RGAA documentée n’est pas une conformité auditée.')
add('E4','C15 · ARCHITECTURE','Séparer présentation, métier et persistance','Une application Django avec des services Python internes.',
 [('PRÉSENTATION','Templates HTML / CSS / JS\n↓\nVues Django et endpoints JSON\n↓\nSessions, auth et CSRF'),('MÉTIER','GameEngine\n↙                     ↘\nLangGraph             Combat\nIA + RAG         règles serveur'),('STOCKAGE / SERVICES','Base Django : comptes / parties.\nSQLite catalogue : références.\nChroma / Ollama : contexte.\nFournisseur externe : génération.')],
 'Le navigateur envoie des actions ; le serveur décide des mutations autorisées.', 'docs/block3/technical-framework-models.md ; services/game_engine.py',
 'Présenter une architecture en couches, pas des microservices déployés qui n’existent pas. Les appels de génération transmettent le contexte utile au service distant. Les secrets restent dans l’environnement. Le schéma est une vue simplifiée ; les modèles du dossier détaillent les flux et les zones de stockage.')
add('E4','C15 · DÉCISIONS TECHNIQUES','Choisir une architecture adaptée au périmètre','Les choix actuels favorisent une démonstration locale reproductible.',
 [('DJANGO','Comptes, sessions, ORM et templates dans un même cadre.\nMoins de couches à exploiter pour ce projet solo.'),('SQLITE / SERVICES IA','Données locales de taille modeste.\nIA hébergée et retrieval local.\nLimites de concurrence et de dépendance externe documentées.'),('CIBLE DE DÉPLOIEMENT','Conteneur web et proxy HTTPS.\nSecrets externes, stockage durable.\nHébergement et SGBD de production à confirmer.')],
 'La préproduction cible est décrite ; son accessibilité réelle reste à prouver.', 'docs/block3/architecture-decisions.md ; technical-framework-models.md',
 'Défendre chaque choix avec ses alternatives et ses conséquences. Ne pas appeler l’environnement local une préproduction déployée. Le référentiel C15 attend une preuve de concept accessible en préproduction et une conclusion de poursuite ; joindre cette preuve. Les critères de sobriété des prestataires restent à compléter lorsque le choix est arrêté.')
add('E4','C16 · ORGANISATION','Piloter un projet solo avec des critères explicites','Backlog, priorités, risques et décisions sont documentés.',
 [('PRÉPARER','Besoin formulé.\nCritères testables.\nComposants concernés.\nRisques et preuve attendue.\nDéfinition de prêt.'),('RÉALISER','Sécurité → cadrage → qualité\n→ industrialisation → exploitation.\nSuivi par éléments de backlog et commits.'),('TERMINER / REVOIR','Code et documentation cohérents.\nTests pertinents.\nPreuve conservée.\nNotes de revue et rétrospective à maintenir.')],
 'Les rituels, dates et échanges réels doivent compléter les supports de pilotage.', 'docs/block3/agile-execution.md ; historique Git',
 'Le dépôt décrit une démarche légère solo avec assistance outillée. Ne pas revendiquer une équipe Scrum, des cérémonies ou des échanges non attestés. Personnaliser calendrier, temps investi, imprévus et arbitrages. Les documents proposent une définition de prêt et de terminé ; l’historique des revues reste à enrichir.')
add('E4','C17 · PARCOURS ET ÉTAT','Conserver une progression cohérente','Le moteur expose des transitions de jeu et des règles de persistance.',
 [('PARCOURS','Accueil → personnage → récit\n↓\nChoix → combat éventuel\n↓\nVictoire, défaite ou poursuite'),('ÉTAT','Anonyme : session Django.\nConnecté : SaveGame + session.\nÉtat sérialisé en JSON.\nPartie terminée non rechargeable.'),('RÈGLES MÉTIER','Combat par session.\nSoins et dégâts côté serveur.\nPropriété des sauvegardes.\nÉchec IA sans progression persistée.')],
 'Les tests portent sur les transitions et les droits, au-delà du rendu des pages.', 'src/django/game/models.py ; services/ ; tests.py',
 'Décrire comment une vue délègue au moteur puis décide de persister. Les tests de sauvegarde couvrent l’échec du service IA, les fins de partie et la propriété. Le jeu implique des tirages aléatoires, mais ces règles ne sont pas décidées par le modèle ; les tests contrôlent l’aléatoire pour vérifier les résultats.')
add('E4','C17 · SÉCURITÉ','Protéger les requêtes et les données du joueur','Des contrôles concrets, avec des limites de production identifiées.',
 [('REQUÊTES','CSRF sur les POST navigateur.\nTaille JSON limitée.\nQuota sur les routes IA.\nContenu dynamique via textContent.'),('PROPRIÉTÉ / SECRETS','Filtres par utilisateur.\nÉtat de combat isolé.\nSecret et hôtes de production via environnement.'),('LIMITES','Audit dépendances à compléter.\nCache partagé pour plusieurs instances.\nRevue des appels longs et de la concurrence du graphe.')],
 'Les protections du navigateur ont évolué : le code courant prime sur les anciennes notes.', 'docs/block3/security-threat-model.md ; game/views.py ; tests.py',
 'Le test CSRF exécuté utilise api_play comme route représentative ; ne pas affirmer qu’il teste individuellement chaque POST. D’autres contrôles testent 413, quota et propriété. Les anciennes notes bloc 1/2 mentionnent encore des exemptions CSRF ; les documents bloc 3 et le code courant décrivent leur migration. Aucun audit global OWASP n’est revendiqué.')
add('E4','C17 · ACCESSIBILITÉ ET SOBRIÉTÉ','Rendre les interactions perceptibles et maîtrisées','Améliorations présentes ; validation manuelle encore nécessaire.',
 [('INTERACTIONS','Annonces de statut dynamiques.\nOnglets avec sémantique ARIA.\nFocus après mise à jour.\nBarres de vie exposées comme progression.'),('VÉRIFICATION MANUELLE','Parcours au clavier.\nContrastes et zoom 200 %.\nLecteur d’écran.\nQualité des textes FR / EN.'),('SOBRIÉTÉ','Appels de jeu déclenchés par action.\nRéutilisation du retrieval.\nImages locales.\nPoids et consommation à mesurer.')],
 'La présence d’attributs ARIA ne suffit pas à valider l’accessibilité réelle.', 'docs/block3/product-quality-audit.md ; ProductQualityTemplateTests',
 'Les tests exécutés lisent des templates ou leurs réponses HTML ; ils ne font pas fonctionner un lecteur d’écran ni le JavaScript dans un navigateur. L’écoconception repose sur des pratiques, sans score environnemental mesuré. Le dépôt mentionne une ancienne taille Docker : elle n’a pas été revérifiée et n’est pas affichée comme résultat actuel.')
add('E4','C18 · CONTRÔLES AUTOMATISÉS','44 tests ciblés réussis sur le bloc applicatif','Vérifications locales du 14 septembre 2026.',
 [('LOT EXÉCUTÉ','Combat et isolation.\nSécurité des requêtes.\nTemplates et parcours simulé.\nSauvegardes, personnages, métriques.'),('MIGRATIONS','makemigrations --check\n--dry-run\n\nAucun changement détecté.\nAucune migration créée.'),('CI VERSIONNÉE','PR, push main / master, manuel.\nLint, checks, tests et couverture.\nDépendances verrouillées.\nRésultats distants à joindre.')],
 '44 tests ne désignent ni la suite complète ni un pourcentage de couverture.', 'preuves/verification.md ; .github/workflows/block3-ci-cd.yml',
 'Le lot a terminé en 6,091 secondes : c’est une durée de tests, pas une performance de l’application. BrowserSmokeJourneyTests utilise le client Django et un moteur simulé, sans navigateur réel. Le seuil de couverture configuré reste 55 %, mais la couverture n’a pas été recalculée pour ce support. Aucune exécution CI distante n’a été consultée.')
add('E4','C19 · LIVRAISON','Construire, vérifier et conserver le même artefact','Le conteneur constitue l’unité de livraison prévue.',
 [('BUILD / SMOKE','Dockerfile Python 3.12.\nInstallation verrouillée.\nDémarrage Gunicorn.\nImage taguée SHA, test /health puis export tar en CI.'),('EXPLOITATION','Configuration par environnement.\nDonnées persistantes à prévoir.\nMigrations au démarrage local.\nÉtape de release à contrôler en production.'),('PROMOTION / RETOUR','Déployer le digest vérifié.\nConserver l’image précédente.\nContrôler la compatibilité DB.\nRejouer santé et parcours.')],
 'Le job staging est un placeholder : il ne déploie pas encore l’application.', '.github/workflows/block3-ci-cd.yml ; Dockerfile ; docs/block3/ci-cd-delivery.md',
 'Le job staging-deploy-placeholder affiche des instructions : il n’y a aucune commande de déploiement effectif. Ne pas assimiler permission packages:write à une publication d’image. Le health de conteneur utilise une clé factice dans le workflow et ne prouve pas une génération IA. Joindre digest, URL de staging et preuve de rollback réels avant de revendiquer la chaîne complète.')
add('E4','E4 · DÉMONSTRATION','Montrer le parcours, puis les garanties','Séquence préparée : 1 min 40, dans un environnement de démonstration.',
 [('00:00 → 00:35','Ouvrir une aventure et un personnage déjà prêts.\nAfficher récit et choix.\nExécuter une action de jeu.'),('00:35 → 01:10','Montrer une sauvegarde du compte de test et sa reprise.\nPrésenter le résultat du test de propriété.'),('01:10 → 01:40','Afficher les résultats locaux et le workflow.\nNommer les preuves manquantes.\nIntroduire le cas d’incident E5.')],
 'Prévoir une capture de secours ; annoncer toute simulation utilisée.', 'docs/block3/traceability.md ; preuves/verification.md',
 'Les autres slides sont également prévues sur 100 secondes, soit E4 en 20 minutes. Préparer les onglets, une sauvegarde de test et le contexte sans données réelles. Une capture du produit n’a pas été créée pendant ce travail. La démonstration manuelle complète et la génération réelle nécessitent l’environnement configuré ; les tests seuls ne les remplacent pas.')

add('E5','E5 · C20 ET C21','Surveiller et résoudre un incident technique','Cas étudié : interférence entre deux combats dans un même processus.',
 [('SURVEILLER','Métriques, journaux et règles d’alerte du projet.\nDistinguer fonctionnement technique et intégrité métier.'),('REPRODUIRE','Ancien code extrait de Git.\nDeux états A et B.\nImbrication déterministe.\nAucun incident de production supposé.'),('VÉRIFIER','Comparer avant / après.\nIdentifier le correctif versionné.\nExpliquer les limites et les suites opérationnelles.')],
 'E5 : 10 minutes ; dossier technique complémentaire joint au support.', 'Référentiel, p. 17 et 22–23 ; Dossier_incident_E5.md',
 'Le référentiel accepte un contexte réel ou fictif avec erreur technique. Ici, la cause et le correctif sont historiques ; la reproduction a été réalisée le 14 septembre 2026 pour la soutenance. Ne pas inventer une alerte utilisateur, un ticket, une date de découverte ou un impact de production. Le dossier joint précise le périmètre de la reconstruction.')
add('E5','C20 · SURVEILLANCE','Observer le parcours complet du joueur','Django /metrics → Prometheus → Grafana ; journaux de services en console.',
 [('APPLICATION','Démarrages, tours et résultats.\nCombats et actions.\nDélai navigateur jusqu’au retour de choix utilisables.'),('SERVICES IA','Opérations, tentatives et retries.\nDurée logique incluant reprises.\nÉchecs, sorties invalides et RAG.\nCoût estimé si tarifs configurés.'),('JOURNAUX','Date, niveau, logger, message.\nLoggers agents et retrieval.\nErreurs contextualisées.\nContenu à revoir avant partage.')],
 'Les métriques évitent les identités ; les messages et traces doivent aussi être contrôlés.', 'docs/monitoring.md ; settings.py ; src/observability/metrics.py',
 'La durée navigateur ne couvre que les retours de récit avec choix utilisables : combats, fins et erreurs sont exclus. Ce n’est donc pas une latence de toutes les requêtes. Le format des logs est du texte à champs, pas du JSON. Les exceptions peuvent produire du contenu sensible ; ne pas déclarer une anonymisation universelle. La stack n’a pas été démarrée pour ces slides.')
add('E5','C20 · SEUILS ET DÉTECTION','Les alertes techniques ne détectent pas tout','Règles existantes dans monitoring/prometheus/alerts.yml.',
 [('INDISPONIBILITÉ','Plus de 2 opérations indisponibles sur 10 min.\nCondition maintenue 2 min.\nSignal pour diagnostic fournisseur.'),('LATENCE / QUALITÉ','p95 > 30 s sur fenêtre 15 min, pendant 10 min.\nSortie invalide : fenêtre 15 min, maintien 1 min.'),('ANGLE MORT MÉTIER','Un combat peut renvoyer HTTP 200 tout en modifiant le mauvais état.\nAucune règle actuelle ne détecte cet invariant.')],
 'Le récepteur Alertmanager est vide : aucune réception externe démontrée.', 'monitoring/prometheus/alerts.yml ; monitoring/alertmanager/alertmanager.yml',
 'La règle indisponibilité opère par série, sans somme explicite ; ne pas la présenter comme un total global agrégé. Pour l’incident d’isolation, proposer un contrôle synthétique ou un compteur d’invariants, mais le nommer comme amélioration future. Les règles de seuil existent ; leur déclenchement et leur livraison doivent encore être montrés dans un bac à sable.')
add('E5','C21 · REPRODUCTION','L’ancienne version attaque le mauvais monstre','Scénario contrôlé : chaque monstre démarre à 8 PV ; dégâts fixés à 3.',
 [('1 / RESTAURER A','Le processus charge le joueur A et son monstre dans des variables globales.'),('2 / RESTAURER B','Avant l’attaque de A, B charge son combat.\nLes mêmes variables globales pointent maintenant vers B.'),('3 / REPRENDRE A','L’action destinée à A utilise l’état global de B.\nMonstre A : 8 PV.\nMonstre B : 5 PV.')],
 'Attendu : A perd 3 PV ; observé avant correctif : B perd 3 PV.', 'reproduce_incident.py ; preuves/incident-combat.json',
 'Expliquer l’imbrication plutôt qu’une concurrence supposée mesurée : restaurer A, restaurer B, puis reprendre l’attaque initiée pour A. Le script lit la version parent du correctif et l’exécute dans un module isolé. Il ne change ni la branche, ni le code du jeu, ni les bases. Ce n’est pas un test de charge HTTP multi-thread.')
add('E5','C21 · CAUSE RACINE','Un état global partage une identité implicite','La sélection du combat dépendait du dernier appel de restauration.',
 [('AVANT','player et current_monster au niveau du module.\nrestore_combat remplace leurs références.\nplayer_action les lit implicitement.'),('MÉCANISME','Chaque session web possède ses données, mais la fonction métier réutilise une mémoire de processus partagée.'),('CONSÉQUENCE','Une interruption entre restauration et résolution peut cibler un autre combat.\nLes compteurs HTTP ne voient pas cette erreur métier.')],
 'L’isolement de la session web doit être conservé jusque dans les fonctions métier.', 'Git : parent de 8a3cf39, src/combat/core.py ; diff game_engine.py',
 'La preuve de cause est le code historique et sa reproduction. Écarter l’hypothèse d’un calcul de dégâts erroné : les dégâts sont fixes et corrects, mais appliqués à la mauvaise référence. L’ancien adaptateur restaurait bien l’état avant l’action ; cela ne protégeait pas contre une autre restauration intercalée.')
add('E5','C21 · CORRECTION','Passer le combat explicitement aux fonctions','Correctif versionné le 3 septembre 2026 : commit 8a3cf39.',
 [('OBJET DÉDIÉ','CombatSession regroupe joueur, monstre, journal et défense.\nUne instance liée à l’état traité.'),('APPELS EXPLICITES','restore_combat_session(...)\n↓\nresolve_player_action(session, action)\n↓\nresolve_monster_attack(session)'),('MISE À JOUR LOCALE','GameEngine récupère joueur et monstre dans cette instance, puis met à jour son état de partie.')],
 'La résolution du combat Django ne dépend plus du dernier combat restauré globalement.', 'src/combat/core.py ; services/game_engine.py ; commit 8a3cf39',
 'Décrire la correction telle qu’elle existe, sans s’en attribuer une réalisation aujourd’hui. Le changement historique est dans un commit plus large, pas dans une PR dédiée à cet incident. Il reste des limites de concurrence sur le graphe ou des requêtes visant une même sauvegarde ; la correction ne prouve pas que toute l’application est thread-safe.')
add('E5','C21 · VALIDATION','Le même scénario touche désormais le bon état','Résultats vérifiés le 14 septembre 2026.',
 [('AVANT CORRECTIF','Monstre A : 8 → 8 PV.\nMonstre B : 8 → 5 PV.\n\nLe mauvais combat est modifié.'),('CODE ACTUEL','Monstre A : 8 → 5 PV.\nMonstre B : 8 → 8 PV.\n\nL’action reste dans la session A.'),('RÉGRESSION','Test d’isolation Django réussi.\n44 tests applicatifs ciblés réussis.\nCas absent / invalide et reprise de combat également exercés.')],
 'L’imbrication est prouvée ; la montée en charge et les requêtes simultanées restent à tester.', 'preuves/incident-combat.json ; game.tests.CombatEngineTests',
 'Le script avant/après et le test Django ne sont pas identiques : le premier reproduit une imbrication au niveau des fonctions cœur ; le second exécute successivement des actions sur deux états et vérifie leurs HP. Les deux se complètent. Ne pas appeler cela un benchmark concurrent ni une preuve de réparation des parties historiques.')
add('E5','E5 · CAPITALISATION','Relier le correctif à l’exploitation','Une résolution documentée et des actions opérationnelles encore à compléter.',
 [('PREUVES DISPONIBLES','Scénario, cause et correctif.\nCommit historique identifié.\nReproduction avant / après.\nTest de non-régression et commandes.'),('À JOINDRE','Ticket dans l’outil de suivi.\nChronologie de découverte réelle.\nAlerte reçue en environnement test.\nDéploiement du correctif et contrôle après livraison.'),('PRÉVENIR','Tester les invariants métier.\nRevoir les autres états partagés.\nTester concurrence et charge.\nMettre à jour le guide de diagnostic.')],
 'Le dossier E5 distingue les faits historiques, la reconstruction et les actions proposées.', 'Dossier_incident_E5.md ; preuves/verification.md',
 'Conclure sur une cause comprise, un correctif versionné et un résultat vérifié. Le document rédigé aujourd’hui n’est pas un ticket créé au moment de l’incident. La boucle d’amélioration ajuste l’application et ses tests ; elle n’entraîne pas automatiquement le modèle de génération. Utiliser les annexes pour les commandes et questions.')

add('ANNEXE','ANNEXE A · COMMANDES','Rejouer les preuves sans toucher au jeu','Depuis la racine du dépôt ; aucune génération réelle requise.',
 [('AVANT / APRÈS','uv run python\ncertif/presentation-bloc3/\nreproduce_incident.py\n\nAncien code lu via Git.'),('TEST D’ISOLATION','uv run python\nsrc/django/manage.py test\ngame.tests.CombatEngineTests\n--noinput'),('MIGRATIONS','uv run python\nsrc/django/manage.py\nmakemigrations --check\n--dry-run')],
 'Les commandes exactes et le lot complet figurent dans preuves/verification.md.', 'reproduce_incident.py ; preuves/verification.md',
 'Les lignes des cartes sont coupées pour projection ; copier les commandes complètes depuis le dossier. La reproduction requiert l’historique Git contenant le parent de 8a3cf39. Aucun git switch, reset ou retour de base n’est nécessaire.')
add('ANNEXE','ANNEXE B · C14 À C21','Retrouver les pièces du dossier','Documentation applicative sous docs/block3/.',
 [('CADRAGE / RÉALISATION','C14 : besoins et traçabilité.\nC15 : modèles et décisions.\nC16 : backlog et revues.\nC17 : code, qualité et sécurité.'),('QUALITÉ / LIVRAISON','C18 : tests et workflow CI.\nC19 : Dockerfile, artefact et procédure de promotion.\nPreuves distantes à ajouter.'),('EXPLOITATION','C20 : monitoring, règles et logs.\nC21 : dossier d’incident, correctif Git et reproduction.\nTicket et déploiement à ajouter.')],
 'Les statuts des anciennes notes peuvent être en retard sur le code : dater les preuves.', 'docs/block3/ ; docs/monitoring.md ; Dossier_incident_E5.md',
 'Ne pas confondre le modèle de diagramme C4 avec la compétence C4 du bloc 1. Les références au référentiel concernent les PDF locaux fournis. Compléter aussi l’identité, les dates, le budget, l’hébergement et l’audit manuel demandés par le dossier de certification.')
add('ANNEXE','ANNEXE C · QUESTIONS','Expliquer les frontières de la preuve','Trois questions probables du jury.',
 [('EST-CE DÉPLOYÉ ?','Le packaging et la procédure existent. Le job staging reste à compléter ; aucune mise en production prouvée ici.'),('EST-CE ACCESSIBLE ?','Des améliorations et tests de structure existent. Clavier, contraste, zoom et lecteur d’écran restent à auditer.'),('INCIDENT DÉTECTÉ COMMENT ?','Défaut historique reconstruit par imbrication contrôlée. Aucune alerte de production ni détection automatique de ce défaut n’est revendiquée.')],
 'Présenter exactement ce qui a été observé, testé et livré.', 'preuves/verification.md ; docs/block3/README.md',
 'Préparer également : distinction CI/CD, copie de l’état versus isolation, mise à jour concurrente d’une même partie, limites du health, protection des journaux et rollback de migrations. Montrer la preuve adaptée plutôt que généraliser les résultats du lot ciblé.')

assert sum(s['seconds'] for s in slides if s['part']=='E4')==1200
assert sum(s['seconds'] for s in slides if s['part']=='E5')==600
render('Presentation_Bloc3',slides)
render('Presentation_E4',[s for s in slides if s['part']=='E4'])
render('Presentation_E5',[s for s in slides if s['part'] in {'E5','ANNEXE'}])
(OUT/'Notes_orales_Bloc3.md').write_text((OUT/'Notes_Presentation_Bloc3.md').read_text(encoding='utf-8'),encoding='utf-8')
